### ISSUE TITLE
Exception in thread rx: IOError "Invalid Argument" in colorama/ansitowin32.py

### ISSUE THREAD

**Issue by virtualnobi** [wendlers/mpfshell#80]
So far, mpfshell has helped us a lot for a fun iot game idea - thanks! Since a few days, however, (without me knowing that I changed something in the installation), mpfshell crashes when I press RST on the esp board. Error message below. 

I re-installed mpfshell using "pip install mpfshell", all dependencies are ok, it says. But somehow... 

Exception in thread rx:
Traceback (most recent call last):
  File "c:\program files\python\2.7\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\program files\python\2.7\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "N:\languages\python\serial\tools\miniterm.py", line 448, in reader
    self.console.write_bytes(data)
  File "N:\languages\python\serial\tools\miniterm.py", line 63, in write_bytes
    self.byte_output.write(byte_string)
  File "N:\languages\python\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "N:\languages\python\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "N:\languages\python\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "N:\languages\python\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 22] Invalid argument

Thanks, nobi

**Comment by skorokithakis** [comment]
Hmm, that's odd. It's never done it for me so far. I'd appreciate it if you could debug some more and figure out why this is happening.
